# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 049f3901f8a789952938a6e8a85a87e51a22fdcd2bbb92ef2435a3a56a6790538a66280fa2f6bcd75a694da27b13340607d6e25e3b849bbc022fa59e4e355b79

test:
  secret_key_base: e44ad6c67312514b616e4c53e8aeb8c1447e6655d87c4ed926a7c3f893dae862e0ab96c77c1cf04d4432e84bc7d0f7e2d70d55724254635180d15d4412e63f67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
